### PR TITLE
Prototype Algorithm. 

### PR DESCRIPTION
**Pull request by oberonia78**

### CODE REVIEW

**Comment by oberonia78** [comment]
Hi @nemo794 I think this PR is ready to use. I'll also share the demo-runconfig to test this.

**Review by chuckwondo — COMMENTED** [review]
@oberonia78, you should not be committing anything under src/dist. We should perhaps schedule a brief call with @nemo794 to discuss the repo structure. Please look at the structure of the `dps` branch, which I plan to merge into `main`. @nemo794, do you have any concerns with my merging `dps` into `main`? If not, please approve my PR.

**Review by chuckwondo — COMMENTED** [review]
@oberonia78, you should _not_ add `.gitignore`. I already added that to the `dps` branch, so this will end up conflicting with that once things are merged. Also, again. There should be no `src/dist` directory committed. Let's please discuss on a call before you attempt making any more changes.

**Comment by chuckwondo** [comment]
@oberonia78, I've deleted the `develop` branch, which automatically closed this PR.

I also merged the `dps` branch into `main`.

I previously discussed with @nemo794 that we'll keep our branch workflow very simple, which is why I deleted the `develop` branch.

We'll follow this branch workflow since this code should be small and we are also a very small team, so there's no need for additional complexity. To start new work:

1. Checkout `main` and `pull` the latest code
2. Create a new branch from the latest `main` code
3. Commit and push code to your new branch
4. When ready, open a PR from your new branch to `main`

I'm going to send you a meeting invite for later this week so we can discuss what you want to put into a new PR.

**Comment by chuckwondo** [comment]
@oberonia78, also, you should have access directly to this repo, so there's no need for you to maintain a fork, if you don't want to.

**Pull request closed without merging**
